-- =========================================================================
-- 00_BOOTSTRAP_ADMIN.sql - SYS chi dung de cap quyen ban dau cho BV_ADMIN
-- =========================================================================

CONNECT SYS/"NtMl1504:))"@localhost:1521/XEPDB1 AS SYSDBA

BEGIN
    EXECUTE IMMEDIATE 'CREATE USER BV_ADMIN IDENTIFIED BY "BvAdmin@2026!" DEFAULT TABLESPACE USERS QUOTA 0 ON USERS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1920 THEN RAISE; END IF;
END;
/

GRANT CREATE SESSION TO BV_ADMIN;

-- Quyen quan tri cho cac yeu cau cua do an
GRANT CREATE USER, ALTER USER, DROP USER TO BV_ADMIN;
GRANT CREATE ROLE, DROP ANY ROLE TO BV_ADMIN;
GRANT GRANT ANY ROLE, GRANT ANY PRIVILEGE, GRANT ANY OBJECT PRIVILEGE TO BV_ADMIN;
GRANT SELECT ANY DICTIONARY TO BV_ADMIN;
GRANT SELECT ANY TABLE TO BV_ADMIN;
GRANT UPDATE ANY TABLE TO BV_ADMIN;

GRANT AUDIT_ADMIN, AUDIT_VIEWER TO BV_ADMIN;
GRANT CREATE JOB, MANAGE SCHEDULER TO BV_ADMIN;
GRANT CREATE ANY DIRECTORY, DROP ANY DIRECTORY TO BV_ADMIN;
GRANT EXECUTE ON SYS.DBMS_DATAPUMP TO BV_ADMIN;
GRANT EXECUTE ON SYS.DBMS_DATAPUMP TO BVOWNER;
GRANT DATAPUMP_EXP_FULL_DATABASE TO BVOWNER;
GRANT DATAPUMP_IMP_FULL_DATABASE TO BVOWNER;

-- OLS: SYS chi bootstrap he thong va cap quyen cho admin benh vien
EXEC LBACSYS.CONFIGURE_OLS;
EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;

BEGIN
    LBACSYS.SA_SYSDBA.DROP_POLICY('BV_POLICY');
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    LBACSYS.SA_SYSDBA.CREATE_POLICY(
        policy_name     => 'BV_POLICY',
        column_name     => 'OLS_LABEL',
        default_options => 'READ_CONTROL,LABEL_DEFAULT'
    );
END;
/

-- Authorize BV_ADMIN lam policy admin (chi GRANT role la KHONG DU trong Oracle 21c)
GRANT LBAC_DBA TO BV_ADMIN;
GRANT BV_POLICY_DBA TO BV_ADMIN;
GRANT EXECUTE ON LBACSYS.SA_SYSDBA TO BV_ADMIN;
GRANT EXECUTE ON LBACSYS.SA_COMPONENTS TO BV_ADMIN;
GRANT EXECUTE ON LBACSYS.SA_LABEL_ADMIN TO BV_ADMIN;
GRANT EXECUTE ON LBACSYS.SA_USER_ADMIN TO BV_ADMIN;
GRANT EXECUTE ON LBACSYS.LBAC_POLICY_ADMIN TO BV_ADMIN;
GRANT EXECUTE ON LBACSYS.SA_SESSION TO BV_ADMIN;
GRANT EXECUTE ON LBACSYS.TO_LBAC_DATA_LABEL TO BV_ADMIN;
GRANT EXEMPT ACCESS POLICY TO BV_ADMIN;

-- Buoc quan trong: Dang ky BV_ADMIN la FULL admin cua BV_POLICY
EXEC LBACSYS.SA_USER_ADMIN.SET_USER_PRIVS('BV_POLICY', 'BV_ADMIN', 'FULL');

-- Admin quan ly thong bao OLS
GRANT SELECT, INSERT, UPDATE, DELETE ON BVOWNER.THONGBAO TO BV_ADMIN;

PROMPT === BOOTSTRAP ADMIN DONE ===

