-- =========================================================================
-- 00_BOOTSTRAP_ADMIN.sql - CAP QUYEN QUAN TRI CHO BVOWNER (DBA)
-- BVOWNER = Schema Owner + DBA (gop thanh 1 tai khoan duy nhat)
-- =========================================================================

CONNECT SYS/"NtMl1504:))"@localhost:1521/XEPDB1 AS SYSDBA

-- Quyen quan tri cho cac yeu cau cua do an
GRANT CREATE USER, ALTER USER, DROP USER TO BVOWNER;
GRANT CREATE ROLE, DROP ANY ROLE TO BVOWNER;
GRANT GRANT ANY ROLE, GRANT ANY PRIVILEGE, GRANT ANY OBJECT PRIVILEGE TO BVOWNER;
GRANT SELECT ANY DICTIONARY TO BVOWNER;
GRANT SELECT ANY TABLE TO BVOWNER;
GRANT UPDATE ANY TABLE TO BVOWNER;

GRANT AUDIT_ADMIN, AUDIT_VIEWER TO BVOWNER;
GRANT CREATE JOB, MANAGE SCHEDULER TO BVOWNER;
GRANT CREATE ANY DIRECTORY, DROP ANY DIRECTORY TO BVOWNER;
GRANT EXECUTE ON SYS.DBMS_DATAPUMP TO BVOWNER;
GRANT DATAPUMP_EXP_FULL_DATABASE TO BVOWNER;
GRANT DATAPUMP_IMP_FULL_DATABASE TO BVOWNER;

-- Bypass VPD de BVOWNER xem duoc toan bo du lieu chinh minh so huu
GRANT EXEMPT ACCESS POLICY TO BVOWNER;

-- OLS: SYS bootstrap he thong va cap quyen cho BVOWNER
EXEC LBACSYS.CONFIGURE_OLS;
EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;

BEGIN
    LBACSYS.SA_SYSDBA.DROP_POLICY('BV_POLICY');
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    LBACSYS.SA_SYSDBA.CREATE_POLICY(
        policy_name     => 'BV_POLICY',
        column_name     => 'OLS_LABEL',
        default_options => 'READ_CONTROL,LABEL_DEFAULT'
    );
END;
/

-- Authorize BVOWNER lam policy admin
GRANT LBAC_DBA TO BVOWNER;
GRANT BV_POLICY_DBA TO BVOWNER;
GRANT EXECUTE ON LBACSYS.SA_SYSDBA TO BVOWNER;
GRANT EXECUTE ON LBACSYS.SA_COMPONENTS TO BVOWNER;
GRANT EXECUTE ON LBACSYS.SA_LABEL_ADMIN TO BVOWNER;
GRANT EXECUTE ON LBACSYS.SA_USER_ADMIN TO BVOWNER;
GRANT EXECUTE ON LBACSYS.LBAC_POLICY_ADMIN TO BVOWNER;
GRANT EXECUTE ON LBACSYS.SA_SESSION TO BVOWNER;
GRANT EXECUTE ON LBACSYS.TO_LBAC_DATA_LABEL TO BVOWNER;

-- Dang ky BVOWNER la FULL admin cua BV_POLICY
EXEC LBACSYS.SA_USER_ADMIN.SET_USER_PRIVS('BV_POLICY', 'BVOWNER', 'FULL');

PROMPT === BOOTSTRAP ADMIN DONE ===
