-- =========================================================================
-- 00_CLEANUP.sql - DỌN DẸP CẤU TRÚC CŨ
-- Chạy với quyền SYS AS SYSDBA trên XEPDB1
-- =========================================================================

-- Xóa VPD Policies
BEGIN
    DBMS_RLS.DROP_POLICY('BVOWNER', 'NHANVIEN', 'POL_NV_SELF');
    DBMS_RLS.DROP_POLICY('BVOWNER', 'BENHNHAN', 'POL_BN_SELF');
    DBMS_RLS.DROP_POLICY('BVOWNER', 'HSBA', 'POL_HSBA_BACSI');
    DBMS_RLS.DROP_POLICY('BVOWNER', 'HSBA_DV', 'POL_HSBADV_KTV');
    DBMS_RLS.DROP_POLICY('BVOWNER', 'BENHNHAN', 'POL_BN_BACSI');
    DBMS_RLS.DROP_POLICY('BVOWNER', 'DONTHUOC', 'POL_DT_BACSI');
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Xóa package VPD
BEGIN
    EXECUTE IMMEDIATE 'DROP PACKAGE BVOWNER.BV_VPD_PKG';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Xóa tables (cascade)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BVOWNER.DONTHUOC CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE BVOWNER.HSBA_DV CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE BVOWNER.HSBA CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE BVOWNER.BENHNHAN CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE BVOWNER.NHANVIEN CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE BVOWNER.THONGBAO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Xóa views
BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW BVOWNER.V_CURRENT_NHANVIEN';
    EXECUTE IMMEDIATE 'DROP VIEW BVOWNER.V_CURRENT_BENHNHAN';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Xóa sequences
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE BVOWNER.SEQ_MANV';
    EXECUTE IMMEDIATE 'DROP SEQUENCE BVOWNER.SEQ_MABN';
    EXECUTE IMMEDIATE 'DROP SEQUENCE BVOWNER.SEQ_MAHSBA';
    EXECUTE IMMEDIATE 'DROP SEQUENCE BVOWNER.SEQ_MATB';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Xóa users mẫu (nhân viên + bệnh nhân)
DECLARE
    CURSOR c_users IS
        SELECT username FROM dba_users
        WHERE username LIKE 'BS_%' OR username LIKE 'DPV_%'
           OR username LIKE 'KTV_%' OR username LIKE 'BN_%'
           OR username LIKE 'OLS_U%'
           OR username = 'BVOWNER';
BEGIN
    FOR r IN c_users LOOP
        EXECUTE IMMEDIATE 'DROP USER "' || r.username || '" CASCADE';
    END LOOP;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Xóa OLS policy cũ
BEGIN
    LBACSYS.SA_SYSDBA.DROP_POLICY('BV_POLICY');
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Xóa roles
BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE ROLE_BACSI';
    EXECUTE IMMEDIATE 'DROP ROLE ROLE_DIEUPHOI';
    EXECUTE IMMEDIATE 'DROP ROLE ROLE_KTV';
    EXECUTE IMMEDIATE 'DROP ROLE ROLE_BENHNHAN';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

PROMPT === CLEANUP DONE ===
