-- =========================================================================
-- YC3.sql - Yeu cau 3: Kiem toan
-- =========================================================================

CONNECT BVOWNER/BVOwner#2026@localhost:1521/XEPDB1

-- Dung script co the chay lap: noaudit/drop truoc khi create lai
BEGIN EXECUTE IMMEDIATE 'NOAUDIT POLICY AUD_POL_SESSION'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP AUDIT POLICY AUD_POL_SESSION'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'NOAUDIT POLICY AUD_POL_SELECT_BN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP AUDIT POLICY AUD_POL_SELECT_BN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'NOAUDIT POLICY AUD_POL_DML_HSBA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP AUDIT POLICY AUD_POL_DML_HSBA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'NOAUDIT POLICY AUD_POL_DML_DT BY BS_001, BS_002, BS_003'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP AUDIT POLICY AUD_POL_DML_DT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'NOAUDIT POLICY AUD_POL_PROC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP AUDIT POLICY AUD_POL_PROC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'NOAUDIT POLICY AUD_POL_GRANT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP AUDIT POLICY AUD_POL_GRANT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'NOAUDIT POLICY AUD_POL_ILLEGAL_HSBA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP AUDIT POLICY AUD_POL_ILLEGAL_HSBA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'NOAUDIT POLICY AUD_POL_ILLEGAL_HSBADV'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP AUDIT POLICY AUD_POL_ILLEGAL_HSBADV'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
    DBMS_FGA.DROP_POLICY('BVOWNER', 'DONTHUOC', 'FGA_UPDATE_DONTHUOC');
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    DBMS_FGA.DROP_POLICY('BVOWNER', 'HSBA', 'FGA_UPDATE_HSBA_BS');
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE AUDIT POLICY AUD_POL_SESSION ACTIONS LOGON, LOGOFF;
AUDIT POLICY AUD_POL_SESSION;

CREATE AUDIT POLICY AUD_POL_SELECT_BN ACTIONS SELECT ON BVOWNER.BENHNHAN;
AUDIT POLICY AUD_POL_SELECT_BN WHENEVER NOT SUCCESSFUL;
AUDIT POLICY AUD_POL_SELECT_BN WHENEVER SUCCESSFUL;

CREATE AUDIT POLICY AUD_POL_DML_HSBA ACTIONS INSERT, UPDATE, DELETE ON BVOWNER.HSBA;
AUDIT POLICY AUD_POL_DML_HSBA;

CREATE AUDIT POLICY AUD_POL_DML_DT ACTIONS INSERT, UPDATE, DELETE ON BVOWNER.DONTHUOC;
AUDIT POLICY AUD_POL_DML_DT BY BS_001, BS_002, BS_003;

CREATE AUDIT POLICY AUD_POL_PROC ACTIONS EXECUTE ON BVOWNER.BV_VPD_PKG;
AUDIT POLICY AUD_POL_PROC WHENEVER SUCCESSFUL;

CREATE AUDIT POLICY AUD_POL_GRANT
    PRIVILEGES GRANT ANY PRIVILEGE, GRANT ANY OBJECT PRIVILEGE, GRANT ANY ROLE;
AUDIT POLICY AUD_POL_GRANT;

BEGIN
    DBMS_FGA.ADD_POLICY(
        object_schema   => 'BVOWNER',
        object_name     => 'DONTHUOC',
        policy_name     => 'FGA_UPDATE_DONTHUOC',
        audit_condition => '1=1',
        audit_column    => 'MAHSBA,NGAYDT,TENTHUOC,LIEUDUNG',
        enable          => TRUE,
        statement_types => 'UPDATE',
        audit_trail     => DBMS_FGA.DB + DBMS_FGA.EXTENDED
    );
END;
/

BEGIN
    DBMS_FGA.ADD_POLICY(
        object_schema   => 'BVOWNER',
        object_name     => 'HSBA',
        policy_name     => 'FGA_UPDATE_HSBA_BS',
        audit_condition => '1=1',
        audit_column    => 'CHANDOAN,DIEUTRI,KETLUAN',
        enable          => TRUE,
        statement_types => 'UPDATE',
        audit_trail     => DBMS_FGA.DB + DBMS_FGA.EXTENDED
    );
END;
/

CREATE AUDIT POLICY AUD_POL_ILLEGAL_HSBA ACTIONS UPDATE ON BVOWNER.HSBA;
AUDIT POLICY AUD_POL_ILLEGAL_HSBA WHENEVER NOT SUCCESSFUL;

CREATE AUDIT POLICY AUD_POL_ILLEGAL_HSBADV ACTIONS INSERT, UPDATE, DELETE ON BVOWNER.HSBA_DV;
AUDIT POLICY AUD_POL_ILLEGAL_HSBADV WHENEVER NOT SUCCESSFUL;

PROMPT === YC3 DONE ===

